
export const downloadCSV = (csvData: string[][], filename: string) => {
  // Convert to CSV string with proper escaping
  const csvContent = csvData.map(row => 
    row.map(field => {
      // Handle fields that contain commas, quotes, or newlines
      const fieldStr = String(field || '');
      if (fieldStr.includes(',') || fieldStr.includes('"') || fieldStr.includes('\n')) {
        return `"${fieldStr.replace(/"/g, '""')}"`;
      }
      return fieldStr;
    }).join(',')
  ).join('\n');

  // Create and download file
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const formatPlayerName = (player: any): string => {
  return `${player.first_name || ''} ${player.last_name || ''}`.trim() || 'Unknown Player';
};

export const getPlayerFranchiseValue = (player: any): string => {
  // Convert player value from cents to dollars if it exists
  if (player?.fantasy_data_nfl?.fantasy_positions_value) {
    const value = player.fantasy_data_nfl.fantasy_positions_value;
    return `$${(value / 100).toFixed(2)}`;
  }
  return '';
};

export const getPlayerAge = (player: any): string => {
  if (player?.age) {
    return player.age.toString();
  }
  return '';
};

export const getPlayerExperience = (player: any): string => {
  if (player?.years_exp !== undefined) {
    return player.years_exp === 0 ? 'Rookie' : `${player.years_exp} years`;
  }
  return '';
};

export const getDataTimestamp = (): string => {
  return new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    timeZoneName: 'short'
  });
};

export interface ExportOptionsData {
  includeLeagueRules: boolean;
  leagueRules: string;
  includeFAAB: boolean;
  faabBudget: string;
  faabNotes: string;
  includeDraftOrder: boolean;
  draftOrder: string;
  includePlayerDetails: boolean;
  includeAnalytics: boolean;
}

export const addExportOptionsToCSV = (
  csvData: string[][],
  options: ExportOptionsData,
  leagueName: string
): string[][] => {
  const enhancedData = [...csvData];

  // Add export timestamp at the top
  enhancedData.unshift([]);
  enhancedData.unshift([`Data exported on: ${getDataTimestamp()}`]);
  enhancedData.unshift([`League: ${leagueName}`]);
  enhancedData.unshift(['Generated by SleeperSheets - https://sleepersheets.com']);
  enhancedData.unshift([]);

  // Add spacing and additional info sections
  if (options.includeLeagueRules || options.includeFAAB || options.includeDraftOrder) {
    enhancedData.push([]); // Empty row for spacing
    enhancedData.push(['=== ADDITIONAL LEAGUE INFORMATION ===']);
    enhancedData.push([]);
  }

  // Add League Rules
  if (options.includeLeagueRules && options.leagueRules.trim()) {
    enhancedData.push(['LEAGUE RULES & SCORING']);
    enhancedData.push([options.leagueRules]);
    enhancedData.push([]);
  }

  // Add FAAB Information
  if (options.includeFAAB && (options.faabBudget.trim() || options.faabNotes.trim())) {
    enhancedData.push(['FAAB INFORMATION']);
    if (options.faabBudget.trim()) {
      enhancedData.push(['Budget per Team:', options.faabBudget]);
    }
    if (options.faabNotes.trim()) {
      enhancedData.push(['FAAB Notes:', options.faabNotes]);
    }
    enhancedData.push([]);
  }

  // Add Draft Order
  if (options.includeDraftOrder && options.draftOrder.trim()) {
    enhancedData.push(['DRAFT ORDER & DETAILS']);
    enhancedData.push([options.draftOrder]);
    enhancedData.push([]);
  }

  return enhancedData;
};

export const generateAnalyticsCSV = (
  rosters: any[],
  rosterUserMap: Record<string, any>,
  players: Record<string, any>
): string[][] => {
  const csvData: string[][] = [];

  // Headers
  csvData.push(['Team Analytics Summary']);
  csvData.push([]);
  csvData.push(['Team Name', 'Total Players', 'Total Value', 'Avg Player Value', 'QB Count', 'RB Count', 'WR Count', 'TE Count']);

  // Team data
  rosters.forEach(roster => {
    const user = rosterUserMap[roster.roster_id];
    const teamName = user?.display_name || user?.username || 'Unknown Team';
    
    const teamPlayers = roster.players || [];
    const totalPlayers = teamPlayers.length;
    
    // Calculate values and position counts
    let totalValue = 0;
    const positionCounts = { QB: 0, RB: 0, WR: 0, TE: 0 };
    
    teamPlayers.forEach((playerId: string) => {
      const player = players[playerId];
      if (player) {
        // Add to total value
        if (player.fantasy_data_nfl?.fantasy_positions_value) {
          totalValue += player.fantasy_data_nfl.fantasy_positions_value / 100;
        }
        
        // Count positions
        if (player.position && positionCounts.hasOwnProperty(player.position)) {
          positionCounts[player.position as keyof typeof positionCounts]++;
        }
      }
    });
    
    const avgValue = totalPlayers > 0 ? totalValue / totalPlayers : 0;
    
    csvData.push([
      teamName,
      totalPlayers.toString(),
      `$${Math.round(totalValue).toLocaleString()}`,
      `$${Math.round(avgValue).toLocaleString()}`,
      positionCounts.QB.toString(),
      positionCounts.RB.toString(),
      positionCounts.WR.toString(),
      positionCounts.TE.toString()
    ]);
  });

  return csvData;
};
