-- No-op: exact duplicate of 20250910050447.
--
-- This file was byte-for-byte identical to the migration 11 seconds before
-- it. Its statements are a data backfill (reclassifying team defenses as FAAB
-- acquisitions and deleting the matching contract rows), so running them a
-- second time changed nothing in production — the first run had already made
-- the predicates false.
--
-- The body is removed rather than kept, because on a database being built
-- from scratch the pair is not harmless: both files are recorded as applied
-- in production, so deleting this file outright would leave a version in
-- supabase_migrations.schema_migrations with no corresponding migration.
-- Keeping the file and emptying it preserves that record while letting a
-- fresh `supabase db reset` succeed.
