-- No-op: exact duplicate of 20250910051942.
--
-- This file was byte-for-byte identical to the migration 24 seconds before
-- it, and unlike the other duplicated pair its statements are DDL, not a data
-- backfill: bare `CREATE TABLE public.league_metadata`, four
-- `CREATE OR REPLACE FUNCTION`s, four `CREATE POLICY`s and eight
-- `CREATE TRIGGER`s, none of them guarded.
--
-- Against production it was already applied and never re-runs. Against an
-- empty database it is fatal — the second `CREATE TABLE league_metadata`
-- aborts the reset. This was the reason a from-scratch rebuild failed even
-- after the missing tables were accounted for.
--
-- Emptied rather than deleted so the recorded migration version keeps a
-- corresponding file. See the sibling note in
-- 20250910050458_7a237487-3d95-4085-afb5-9eadc9424cd7.sql.
