// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amjdravcumckikfadlwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtamRyYXZjdW1ja2lrZmFkbHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzk3NTksImV4cCI6MjA2MzYxNTc1OX0.7eshJ6gAEQLwZAVuDed2Qg0zqUdYoLzN9Hmw2Gg2mIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);